name: "FAP: Build"
on: [push, pull_request]
jobs:
  ufbt-build-action:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-url: https://github.com/Next-Flip/Momentum-Firmware.git
      - uses: actions/upload-artifact@v4
        with:
          name: capture_monstres-fap
          path: ${{ steps.build-app.outputs.fap-artifacts }}
